### ISSUE TITLE
Export env vars by default

### ISSUE THREAD

**Issue by MSch** [gjaldon/heroku-buildpack-phoenix-static#56]
The Elixir buildpack has moved away from `config_vars_to_export`

https://github.com/HashNuke/heroku-buildpack-elixir/pull/102

**Comment by aaronjensen** [comment]
I like this idea, this was annoying for us.

**Comment by egeersoz** [comment]
I just got burned by this and ended up wasting a couple of hours. :(

**Comment by tsubery** [comment]
Yea, I wasted a lot of time figuring this out too. Opened an [issue](https://github.com/phoenixframework/phoenix_guides/issues/671) on Phoenix guides because that was I was following. Better to [raise](https://github.com/phoenixframework/phoenix_guides/pull/673) on compile time than create a broken build.

**Comment by tsubery** [comment]
Should be [solved](https://github.com/gjaldon/heroku-buildpack-phoenix-static/pull/60) now.

**Comment by aaronjensen** [comment]
Thanks!
